// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using System;
using System.Collections.Generic;
using Dragon.Copilot.Physician.Models;

namespace SampleExtension.Web.Services;

/// <summary>
/// Service that generates Canary Health Screening style adaptive cards.
/// This is a mock implementation that returns sample screening results.
/// </summary>
public static class CanaryHealthScreeningService
{
    private const string CanaryLogo = "https://csstatic.blob.core.windows.net/assets/dragon_canary_logo.png";
    private const string CanaryApiUrl = "https://canaryspeech.com/api";

    /// <summary>
    /// Creates a mock Canary Health Screening response with both note and timeline cards
    /// </summary>
    /// <param name="correlationId">The correlation ID for the request</param>
    /// <returns>A DspResponse containing Canary-style visualization resources</returns>
    public static DspResponse CreateCanaryScreeningResponse(string correlationId)
    {
        var response = new DspResponse
        {
            SchemaVersion = "0.1",
            Document = new Document
            {
                Title = "Clinical Analysis Report",
                Type = new DocumentType
                {
                    Text = "Outpatient Note",
                    Codes = new List<CodeInfo>
                    {
                        new()
                        {
                            System = "LOINC",
                            Identifier = "34109-9",
                            Description = "Note",
                            SystemUrl = new Uri("http://loinc.org")
                        }
                    }
                }
            }
        };

        // Add the note card (detailed version)
        response.Resources?.Add(CreateCanaryNoteCard(correlationId));

        // Add the timeline card (summary version)
        response.Resources?.Add(CreateCanaryTimelineCard(correlationId));

        return response;
    }

    /// <summary>
    /// Creates the detailed note card for Canary Health Screening
    /// </summary>
    private static VisualizationResource CreateCanaryNoteCard(string correlationId)
    {
        var bodyElements = new List<object>
        {
            // Behavioral Health Section
            new
            {
                type = "Container",
                items = new object[]
                {
                    new { type = "TextBlock", text = "Canary Behavioral Health Screening", weight = "Bolder", size = "Small", spacing = "Small" },
                    new
                    {
                        type = "FactSet",
                        spacing = "Small",
                        facts = new object[]
                        {
                            new { title = "•", value = "Additional Screening Recommended" },
                            new { title = "•", value = "Vocal features indicative of Anxiety - low" },
                            new { title = "•", value = "Vocal features indicative of Depression - high" }
                        }
                    }
                }
            },
            // Cognitive Health Section
            new
            {
                type = "Container",
                spacing = "Small",
                items = new object[]
                {
                    new { type = "TextBlock", text = "Canary Cognitive Health Screening", weight = "Bolder", size = "Small", spacing = "Small" },
                    new
                    {
                        type = "FactSet",
                        spacing = "Small",
                        facts = new object[]
                        {
                            new { title = "•", value = "Additional Screening Not Recommended" },
                            new { title = "•", value = "Vocal features indicative of MCI - MCI not detected" },
                            new { title = "•", value = "Vocal features indicative of Alzheimer's - No Alzheimer's Detected" }
                        }
                    }
                }
            },
            // Disclaimer
            new
            {
                type = "Container",
                spacing = "Small",
                items = new object[]
                {
                    new
                    {
                        type = "TextBlock",
                        text = "This information includes AI generated content provided by Canary and is intended to assist healthcare providers (HCP) in evaluating the indication of certain conditions. Check for mistakes in all content generated by AI. This is not a diagnosis, treatment or judgment; further medical evaluation is required to make a health determination in all scenarios. The information is not part of a time-critical decision, nor intended to replace or direct the HCP's judgment or clinical reasoning in all scenarios.",
                        wrap = true,
                        size = "Small",
                        spacing = "Small"
                    }
                }
            }
        };

        return new VisualizationResource
        {
            Id = "canary-speech-screening-001",
            Type = "AdaptiveCard",
            Subtype = VisualizationSubtype.Note,
            CardTitle = "Canary Speech",
            PartnerLogo = CanaryLogo,
            AdaptiveCardPayload = new AdaptiveCardPayload
            {
                Type = "AdaptiveCard",
                Version = "1.3",
                Body = bodyElements
            },
            References = new List<VisualizationReference>
            {
                new()
                {
                    Id = "ref-canary-speech-001",
                    Type = ReferenceType.Web,
                    Title = "Canary Speech",
                    Url = new Uri("https://canaryspeech.com")
                }
            },
            PayloadSources = new List<PayloadSource>
            {
                new()
                {
                    Identifier = "canary-speech-screening-20240908",
                    Description = "Canary Speech AI Health Screening Service",
                    Url = new Uri(CanaryApiUrl)
                }
            },
            DragonCopilotCopyData = GetCopyDataContent()
        };
    }

    /// <summary>
    /// Creates the timeline card for Canary Health Screening (summary version)
    /// </summary>
    private static VisualizationResource CreateCanaryTimelineCard(string correlationId)
    {
        // Timeline card uses the same body/actions structure as the note card
        var bodyElements = new List<object>
        {
            // Behavioral Health Section
            new
            {
                type = "Container",
                items = new object[]
                {
                    new { type = "TextBlock", text = "Canary Behavioral Health Screening", weight = "Bolder", size = "Small", spacing = "Small" },
                    new
                    {
                        type = "FactSet",
                        spacing = "Small",
                        facts = new object[]
                        {
                            new { title = "•", value = "Additional Screening Recommended" },
                            new { title = "•", value = "Vocal features indicative of Anxiety - low" },
                            new { title = "•", value = "Vocal features indicative of Depression - high" }
                        }
                    }
                }
            },
            // Cognitive Health Section
            new
            {
                type = "Container",
                spacing = "Small",
                items = new object[]
                {
                    new { type = "TextBlock", text = "Canary Cognitive Health Screening", weight = "Bolder", size = "Small", spacing = "Small" },
                    new
                    {
                        type = "FactSet",
                        spacing = "Small",
                        facts = new object[]
                        {
                            new { title = "•", value = "Additional Screening Not Recommended" },
                            new { title = "•", value = "Vocal features indicative of MCI - MCI not detected" },
                            new { title = "•", value = "Vocal features indicative of Alzheimer's - No Alzheimer's Detected" }
                        }
                    }
                }
            },
            // Disclaimer
            new
            {
                type = "Container",
                spacing = "Small",
                items = new object[]
                {
                    new
                    {
                        type = "TextBlock",
                        text = "This information includes AI generated content provided by Canary and is intended to assist healthcare providers (HCP) in evaluating the indication of certain conditions. Check for mistakes in all content generated by AI. This is not a diagnosis, treatment or judgment; further medical evaluation is required to make a health determination in all scenarios. The information is not part of a time-critical decision, nor intended to replace or direct the HCP's judgment or clinical reasoning in all scenarios.",
                        wrap = true,
                        size = "Small",
                        spacing = "Small"
                    }
                }
            }
        };

        return new VisualizationResource
        {
            Id = "canary-speech-screening-001",
            Type = "AdaptiveCard",
            Subtype = VisualizationSubtype.Timeline,
            CardTitle = "Canary Speech",
            PartnerLogo = CanaryLogo,
            AdaptiveCardPayload = new AdaptiveCardPayload
            {
                Type = "AdaptiveCard",
                Version = "1.3",
                Body = bodyElements
            },
            References = new List<VisualizationReference>
            {
                new()
                {
                    Id = "ref-canary-speech-001",
                    Type = ReferenceType.Web,
                    Title = "Canary Speech",
                    Url = new Uri("https://canaryspeech.com")
                }
            },
            PayloadSources = new List<PayloadSource>
            {
                new()
                {
                    Identifier = "canary-speech-screening-20240908",
                    Description = "Canary Speech AI Health Screening Service",
                    Url = new Uri(CanaryApiUrl)
                }
            },
            DragonCopilotCopyData = GetCopyDataContent()
        };
    }

    private static string GetCopyDataContent()
    {
        return "Canary Behavioral Health Screening\n" +
               "• Additional Screening Recommended\n" +
               "• Vocal features indicative of Anxiety - low\n" +
               "• Vocal features indicative of Depression - high\n" +
               "\n" +
               "Canary Cognitive Health Screening\n" +
               "• Additional Screening Not Recommended\n" +
               "• Vocal features indicative of MCI - MCI not detected\n" +
               "• Vocal features indicative of Alzheimer's - No Alzheimer's Detected";
    }
}
